name: meiyou_extensions_lib
description: Package used for making extenstions for Meiyou app.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  okhttp:
    git:
      url: https://github.com/Noobware1/okhttp.git
      ref: master
  dart_eval:
    git:
      url: https://github.com/Noobware1/dart_eval.git
      ref: master
  crypto_dart:
    git:
      url: https://github.com/Noobware1/crypto_dart.git
      ref: master
  dartx:
    git:
      url: https://github.com/Noobware1/dartx.git
      ref: master
  html: ^0.15.4
  shared_preferences: ^2.2.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependency_overrides:
  analyzer: ">=5.2.0 <7.0.0"
