name: meiyou_extensions_lib
description: Package used for making extenstions for Meiyou app.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  okhttp:
    git:
      url: https://github.com/Noobware1/okhttp.git
      ref: master
  dart_eval:
    git:
      url: https://github.com/Noobware1/dart_eval.git
      ref: test
  crypto_dart:
    git:
      url: https://github.com/Noobware1/crypto_dart.git
      ref: master
  nice_dart:
    git:
      url: https://github.com/Noobware1/nice_dart.git
      ref: master
  html: ^0.15.4
  isar: 3.1.0+1
  archive: ^3.4.10
  meta: ^1.11.0
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependency_overrides:
  analyzer: ">=6.5.0 <7.0.0"
