name: meiyou_extenstions
description: Package used for making extenstions for Meiyou app.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  dart_eval:
    git:
      url: https://github.com/Noobware1/dart_eval.git
      ref: master
  ok_http_dart:
    git:
      url: https://github.com/Noobware1/ok_http.git
      ref: master
  crypto_dart:
    git:
      url: https://github.com/Noobware1/crypto_dart.git
      ref: master

  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependency_overrides:
  analyzer: ">=5.2.0 <7.0.0"
