import 'package:meiyou_extensions_lib/network.dart';
import 'package:meiyou_extensions_lib/src/lib_overrides.dart';
import 'package:meiyou_extensions_lib/src/models/filter_list.dart';
import 'package:meiyou_extensions_lib/src/models/home_page.dart';
import 'package:meiyou_extensions_lib/src/models/media.dart';
import 'package:meiyou_extensions_lib/src/models/media_details.dart';
import 'package:meiyou_extensions_lib/src/models/media_link.dart';
import 'package:meiyou_extensions_lib/src/models/search_page.dart';
import 'package:meiyou_extensions_lib/src/models/source/catalogue_source.dart';
import 'package:meiyou_extensions_lib/src/utils/utils.dart';
import 'package:meta/meta.dart';
import 'package:okhttp/okhttp.dart';
import 'package:okhttp/request.dart';
import 'package:okhttp/response.dart';

abstract class HttpSource extends CatalogueSource {
  HttpSource();

  /// Network service.
  @protected
  final NetworkHelper network = ExtensionlibOverrides.networkHelper;

  /// Base url of the website without the trailing slash, like: http://mysite.com
  abstract final String baseUrl;

  final int versionId = 1;

  // /// ID of the source. By default it uses a generated id using the first 16 characters (64 bits)
  // /// of the MD5 of the string `"${name.lowercase()}/$lang/$versionId"`.
  // ///
  // /// The ID is generated by the [generateId] function, which can be reused if needed
  // /// to generate outdated IDs for cases where the source name or language needs to
  // /// be changed but migrations can be avoided.
  // ///
  // /// Note: the generated ID sets the sign bit to `0`.
  @override
  late final int id = generateId(name, lang, versionId);

  /// Headers used for requests.
  late final Headers headers = headersBuilder().build();

  OkHttpClient get client => network.client;

  /// Headers builder for requests. Implementations can override this method for custom headers.
  HeadersBuilder headersBuilder() =>
      Headers.Builder().add('User-Agent', network.defaultUserAgentProvider);

  @override
  Future<HomePage> getHomePage(int page, HomePageRequest request) {
    return client
        .newCall(homePageRequest(page, request))
        .execute()
        .then((response) => homePageParse(request, response));
  }

  /// Returns the request for the popular manga given the page.
  ///
  /// * page the page number to retrieve.
  Request homePageRequest(int page, HomePageRequest request);

  /// Parses the response from the site and returns a [MangasPage] object.
  ///
  /// * response the response from the site.
  HomePage homePageParse(HomePageRequest request, Response response);

  @override
  Future<SearchPage> getSearchPage(int page, String query, FilterList filters) {
    return client
        .newCall(searchPageRequest(page, query, filters))
        .execute()
        .then((response) => searchPageParse(response));
  }

  /// Returns the request for the search manga given the page.
  ///
  /// * page the page number to retrieve.
  Request searchPageRequest(int page, String query, FilterList filters);

  /// Parses the response from the site and returns a [SearchResponse] object.
  ///
  /// * response the response from the site.
  SearchPage searchPageParse(Response response);

  @override
  Future<MediaDetails> getMediaDetails(String url) {
    return client
        .newCall(mediaDetailsRequest(url))
        .execute()
        .then((response) => mediaDetailsParse(response));
  }

  Request mediaDetailsRequest(String url) {
    return GET(baseUrl + url, headers: headers);
  }

  Future<MediaDetails> mediaDetailsParse(Response response);

  @override
  Future<List<MediaLink>> getMediaLinks(String url) {
    return client
        .newCall(mediaLinksRequest(url))
        .execute()
        .then((response) => medialinksParse(response));
  }

  Request mediaLinksRequest(String url) {
    return GET(url, headers: headers);
  }

  List<MediaLink> medialinksParse(Response response);

  @override
  Future<Media?> getMedia(MediaLink link) {
    try {
      return client
          .newCall(mediaRequest(link))
          .execute()
          .then((response) => mediaParse(response));
    } on UnsupportedError {
      return Future.value(null);
    } catch (e) {
      rethrow;
    }
  }

  Request mediaRequest(MediaLink link) {
    return throw UnsupportedError('Not implemented');
  }

  Future<Media?> mediaParse(Response response) {
    return throw UnsupportedError('Not implemented');
  }
}
